version: "3.9"
services:
  mysql-school:
    container_name: mysql-school
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Andrea_1204
      MYSQL_DATABASE: mvsc_students
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - msvc-school
  postgres-school:
    container_name: postgres-school
    image: postgres:13.2
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: Andrea_1204
      POSTGRES_DB: msvc_course
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - msvc-school
  mvsc-student:
    container_name: mvsc-student
    image: jcsolis78/students
#    build:
#      context: ./
#      dockerfile: ./mvsc-usuario/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - mvsc-usuario/.env
    networks:
      - msvc-school
    depends_on:
      - mysql-school
    restart: always
  msvc-course:
    container_name: msvc-course
    image: jcsolis78/courses
#    build:
#      context: ./
#      dockerfile: ./mvsc-course/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - mvsc-course/.env
    networks:
      - msvc-school
    depends_on:
      - postgres-school
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  msvc-school:
    name: msvc-school
